name: Lint and Test

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read
  checks: write

jobs:
  Test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python (version specified in .python-version)
      uses: actions/setup-python@v3

    - name: Install poetry and dependencies
      run : |
        pip install poetry
        poetry install

    - name: Lint with Trunk
      uses: trunk-io/trunk-action@v1

    - name: Test with pytest
      run: poetry run pytest
